# Generated by Django 3.1.2 on 2021-01-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('description', models.CharField(default=None, max_length=500)),
                ('year_published', models.CharField(default=None, max_length=5)),
                ('article_type', models.CharField(choices=[('PU', 'Publication'), ('RP', 'Report'), ('OT', 'Other')], default='OT', max_length=2)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='research/%Y/')),
                ('link', models.URLField(blank=True)),
                ('authors', models.ManyToManyField(to='research.Author')),
            ],
        ),
    ]
