# Generated by Django 3.1.2 on 2021-01-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='url_link',
            field=models.URLField(blank=True),
        ),
    ]
