# Generated by Django 3.1.2 on 2021-01-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20210121_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='research/%Y/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='month_published',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='year_published',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
