# Generated by Django 3.1.2 on 2021-01-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20210129_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='month_published',
        ),
        migrations.RemoveField(
            model_name='article',
            name='year_published',
        ),
        migrations.AddField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
