# Generated by Django 3.1.2 on 2021-01-29 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_remove_article_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_published',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 29)),
        ),
    ]
