# Generated by Django 3.1.2 on 2021-01-29 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_remove_article_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_published',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
