# Generated by Django 3.1.2 on 2021-01-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_article_date_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_published',
        ),
    ]
