# Generated by Django 3.1.2 on 2021-01-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0014_auto_20210129_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
