# Generated by Django 3.1.2 on 2021-02-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0016_auto_20210205_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
    ]
