# Generated by Django 3.1.2 on 2021-01-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogpost',
        ),
    ]
