# Generated by Django 3.2 on 2021-04-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_blog_post_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='copy_sent',
            field=models.BooleanField(default=False),
        ),
    ]
